### ISSUE TITLE
腾讯视频除了签到其他任务都失败啊

### ISSUE THREAD

**Issue by nsyncxy1** [pytwj/My-Actions#5]
腾讯视频会员下载任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员观看任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员赠送任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});

**Comment by pytwj** [comment]
任务需要自己手动完成
